# Start from our base image
FROM python:3.10-slim

# Install subversion, which we need to download folders from GitHub
RUN apt-get update && apt-get install -y subversion && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .
